/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ispeak_handgesture_MyNDK */

#ifndef _Included_com_ispeak_handgesture_MyNDK
#define _Included_com_ispeak_handgesture_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
